name: CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v7
      - name: starting the job
        run: echo Job has started..
      - name: displayin date and time
        run: date
      - name: completion
        run: echo Task is completed.
