name: Wlcm

on: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v7
      - name: welcoming..
        run: echo Hello, Welcome!
      
